#pragma once

// From glfw3.h
#define BRICKENGINE_MOUSE_BUTTON_1         0
#define BRICKENGINE_MOUSE_BUTTON_2         1
#define BRICKENGINE_MOUSE_BUTTON_3         2
#define BRICKENGINE_MOUSE_BUTTON_4         3
#define BRICKENGINE_MOUSE_BUTTON_5         4
#define BRICKENGINE_MOUSE_BUTTON_6         5
#define BRICKENGINE_MOUSE_BUTTON_7         6
#define BRICKENGINE_MOUSE_BUTTON_8         7
#define BRICKENGINE_MOUSE_BUTTON_LAST      BRICKENGINE_MOUSE_BUTTON_8
#define BRICKENGINE_MOUSE_BUTTON_LEFT      BRICKENGINE_MOUSE_BUTTON_1
#define BRICKENGINE_MOUSE_BUTTON_RIGHT     BRICKENGINE_MOUSE_BUTTON_2
#define BRICKENGINE_MOUSE_BUTTON_MIDDLE    BRICKENGINE_MOUSE_BUTTON_3
